"""`python -m harness.scope` — writes .tokenman/initial-scope.md.

See docs/superpowers/specs/2026-04-18-phase-1-3-scoping-flow-design.md.
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from harness.lib.repo_profile import RepoProfile
from harness.lib.scope_drafter import ScopeDraft


def _fmt_bytes(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KB"
    return f"{n / (1024 * 1024):.1f} MB"


def _fmt_languages(languages: dict[str, int]) -> str:
    if not languages:
        return "none detected"
    items = sorted(languages.items(), key=lambda kv: -kv[1])
    return ", ".join(f"{lang} ({n})" for lang, n in items[:5])


def _render_markdown(
    *,
    draft: ScopeDraft,
    profile: RepoProfile,
    repo_name: str,
    prompt_version: str,
    marketplaces_empty: bool = False,
    today: datetime | None = None,
) -> str:
    when = (today or datetime.now(timezone.utc)).strftime("%Y-%m-%d")

    lines: list[str] = []
    lines.append(f"# Tokenman — Initial scope for {repo_name}")
    lines.append("")
    lines.append(f"_Generated by `python -m harness.scope` on {when}._")
    lines.append(f"_Prompt version: {prompt_version}._")
    lines.append("")

    lines.append("## Repo profile")
    lines.append("")
    lines.append(draft["profile_prose"].strip())
    lines.append("")
    lines.append("**Facts:**")
    lines.append(f"- Languages: {_fmt_languages(profile['languages'])}")
    lines.append(f"- Files: {profile['total_files']}  Size: {_fmt_bytes(profile['total_bytes'])}")
    lines.append(
        f"- Tests: {'yes' if profile['tests_present'] else 'no'}  "
        f"CI: {'yes' if profile['ci_present'] else 'no'}  "
        f"README: {'yes' if profile['readme_present'] else 'no'}"
    )
    lines.append(
        "- Dependency files: "
        + (", ".join(profile["deps_files"]) if profile["deps_files"] else "none")
    )
    lines.append(f"- Commits in last 30 days: {profile['recent_commits_30d']}")
    lines.append("")

    lines.append("## Recommended skills")
    lines.append("")
    if not draft["recommended_skills"]:
        lines.append("No skills from the curated catalog match this repo yet.")
    else:
        for s in draft["recommended_skills"]:
            lines.append(f"- **{s['name']}** — {s['reasoning']}")
            lines.append(f"  _Default cadence:_ {s['default_cadence']}")
    lines.append("")

    lines.append("## Skills considered but skipped")
    lines.append("")
    if not draft["skipped_skills"]:
        lines.append("None.")
    else:
        for s in draft["skipped_skills"]:
            lines.append(f"- **{s['name']}** — {s['reasoning']}")
    lines.append("")

    lines.append("## Candidates for catalog")
    lines.append("")
    lines.append(
        "The scoping pass found plugins that looked relevant but aren't in "
        "`recommended-skills.yaml`. Tokenman will **not** install these. "
        "If you want to use one, open a PR against the tokenman library "
        "adding it to the catalog."
    )
    lines.append("")
    if marketplaces_empty:
        lines.append(
            "_No marketplaces configured. Run `claude plugins marketplace "
            "add <source>` to enable discovery._"
        )
    elif not draft["candidate_uncurated_plugins"]:
        lines.append("None.")
    else:
        for c in draft["candidate_uncurated_plugins"]:
            lines.append(
                f"- **{c['plugin']}** (marketplace: `{c['marketplace']}`) — "
                f"{c['reasoning']}"
            )
    lines.append("")

    lines.append("## Suggested boundaries")
    lines.append("")
    lines.append("### Allowed paths")
    lines.append("")
    allowed = draft["suggested_boundaries"]["allowed"]
    if allowed:
        for p in allowed:
            lines.append(f"- `{p}`")
    else:
        lines.append(
            "None declared — skills operate under their own SKILL.md scopes."
        )
    lines.append("")
    lines.append("### Forbidden paths")
    lines.append("")
    forbidden = draft["suggested_boundaries"]["forbidden"]
    if forbidden:
        for p in forbidden:
            lines.append(f"- `{p}`")
    else:
        lines.append("None.")
    lines.append("")

    lines.append("## What's not here yet")
    lines.append("")
    lines.append(
        "Budget and schedule strategy are declared by the user in "
        "`.tokenman/tokenman.yaml`; automated suggestion lands with Phase 2 "
        "(spec §7). Expected-PR-volume estimation lands with Phase 4 once "
        "the ledger has history to draw on. This scope file is the seed "
        "for that eventual configuration."
    )
    lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    raise SystemExit("harness.scope CLI is not yet implemented (Phase 1.3)")


if __name__ == "__main__":
    sys.exit(main())
