"""`python -m harness.scope` — writes .tokenman/initial-scope.md.

See docs/superpowers/specs/2026-04-18-phase-1-3-scoping-flow-design.md.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from harness.lib import catalog, marketplace, repo_profile, scope_drafter
from harness.lib.repo_profile import RepoProfile
from harness.lib.scope_drafter import ScopeDraft


def _fmt_bytes(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KB"
    return f"{n / (1024 * 1024):.1f} MB"


def _fmt_languages(languages: dict[str, int]) -> str:
    if not languages:
        return "none detected"
    items = sorted(languages.items(), key=lambda kv: -kv[1])
    return ", ".join(f"{lang} ({n})" for lang, n in items[:5])


def _render_markdown(
    *,
    draft: ScopeDraft,
    profile: RepoProfile,
    repo_name: str,
    prompt_version: str,
    marketplaces_empty: bool = False,
    today: datetime | None = None,
) -> str:
    when = (today or datetime.now(timezone.utc)).strftime("%Y-%m-%d")

    lines: list[str] = []
    lines.append(f"# Tokenman — Initial scope for {repo_name}")
    lines.append("")
    lines.append(f"_Generated by `python -m harness.scope` on {when}._")
    lines.append(f"_Prompt version: {prompt_version}._")
    lines.append("")

    lines.append("## Repo profile")
    lines.append("")
    lines.append(draft["profile_prose"].strip())
    lines.append("")
    lines.append("**Facts:**")
    lines.append(f"- Languages: {_fmt_languages(profile['languages'])}")
    lines.append(f"- Files: {profile['total_files']}  Size: {_fmt_bytes(profile['total_bytes'])}")
    lines.append(
        f"- Tests: {'yes' if profile['tests_present'] else 'no'}  "
        f"CI: {'yes' if profile['ci_present'] else 'no'}  "
        f"README: {'yes' if profile['readme_present'] else 'no'}"
    )
    lines.append(
        "- Dependency files: "
        + (", ".join(profile["deps_files"]) if profile["deps_files"] else "none")
    )
    lines.append(f"- Commits in last 30 days: {profile['recent_commits_30d']}")
    lines.append("")

    lines.append("## Recommended skills")
    lines.append("")
    if not draft["recommended_skills"]:
        lines.append("No skills from the curated catalog match this repo yet.")
    else:
        for s in draft["recommended_skills"]:
            lines.append(f"- **{s['name']}** — {s['reasoning']}")
            lines.append(f"  _Default cadence:_ {s['default_cadence']}")
    lines.append("")

    lines.append("## Skills considered but skipped")
    lines.append("")
    if not draft["skipped_skills"]:
        lines.append("None.")
    else:
        for s in draft["skipped_skills"]:
            lines.append(f"- **{s['name']}** — {s['reasoning']}")
    lines.append("")

    lines.append("## Candidates for catalog")
    lines.append("")
    lines.append(
        "The scoping pass found plugins that looked relevant but aren't in "
        "`recommended-skills.yaml`. Tokenman will **not** install these. "
        "If you want to use one, open a PR against the tokenman library "
        "adding it to the catalog."
    )
    lines.append("")
    if marketplaces_empty:
        lines.append(
            "_No marketplaces configured. Run `claude plugins marketplace "
            "add <source>` to enable discovery._"
        )
    elif not draft["candidate_uncurated_plugins"]:
        lines.append("None.")
    else:
        for c in draft["candidate_uncurated_plugins"]:
            lines.append(
                f"- **{c['plugin']}** (marketplace: `{c['marketplace']}`) — "
                f"{c['reasoning']}"
            )
    lines.append("")

    lines.append("## Suggested boundaries")
    lines.append("")
    lines.append("### Allowed paths")
    lines.append("")
    allowed = draft["suggested_boundaries"]["allowed"]
    if allowed:
        for p in allowed:
            lines.append(f"- `{p}`")
    else:
        lines.append(
            "None declared — skills operate under their own SKILL.md scopes."
        )
    lines.append("")
    lines.append("### Forbidden paths")
    lines.append("")
    forbidden = draft["suggested_boundaries"]["forbidden"]
    if forbidden:
        for p in forbidden:
            lines.append(f"- `{p}`")
    else:
        lines.append("None.")
    lines.append("")

    lines.append("## What's not here yet")
    lines.append("")
    lines.append(
        "Budget and schedule strategy are declared by the user in "
        "`.tokenman/tokenman.yaml`; automated suggestion lands with Phase 2 "
        "(spec §7). Expected-PR-volume estimation lands with Phase 4 once "
        "the ledger has history to draw on. This scope file is the seed "
        "for that eventual configuration."
    )
    lines.append("")

    return "\n".join(lines)


_QUESTIONS = [
    ("purpose", "What's this repo for? (one line)"),
    ("concern",
     "Main maintenance concern? [a] docs  [b] dep freshness  "
     "[c] dead code  [d] other"),
    ("off_limits", "Paths off-limits? (comma-separated globs, blank to skip)"),
    ("other", "Anything else the scoping agent should know?"),
]


def _ask_interactive(non_interactive: bool) -> dict[str, str]:
    if non_interactive:
        return {key: "" for key, _ in _QUESTIONS}
    answers: dict[str, str] = {}
    print()
    print("A few questions:")
    print()
    for key, prompt in _QUESTIONS:
        answers[key] = input(f"  {prompt}\n  > ").strip()
        print()
    return answers


def _get_stub_result() -> str:
    path = catalog.tokenman_root() / "tests" / "fixtures" / "scope-captures" / "minimal.json"
    return path.read_text()


def _prompt_accept_edit_abort(rendered: str, non_interactive: bool) -> tuple[str, str]:
    if non_interactive:
        return "accept", rendered
    print("=== Draft initial-scope.md ===")
    print(rendered)
    print("=============================")
    while True:
        choice = input("Accept this draft? [a]ccept / [e]dit / [x] abort > ").strip().lower()
        if choice in ("a", "accept", ""):
            return "accept", rendered
        if choice in ("x", "abort"):
            return "abort", rendered
        if choice in ("e", "edit"):
            editor = os.environ.get("EDITOR", "vi")
            with tempfile.NamedTemporaryFile("w+", suffix=".md", delete=False) as tf:
                tf.write(rendered)
                tmp_path = tf.name
            subprocess.run([editor, tmp_path], check=False)
            edited = Path(tmp_path).read_text()
            Path(tmp_path).unlink(missing_ok=True)
            if not edited.strip():
                return "abort", rendered
            return "accept", edited
        print("  (choose a / e / x)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m harness.scope")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--refresh", action="store_true",
                        help="refresh marketplace caches before reading")
    parser.add_argument("--claude-bin", default="claude")
    parser.add_argument("--output-path", default=None,
                        help="default: <repo>/.tokenman/initial-scope.md")
    parser.add_argument("--non-interactive", action="store_true")
    parser.add_argument("--dry-run", action="store_true",
                        help="use canned LLM response (no claude invocation)")
    args = parser.parse_args(argv)

    repo = Path(args.repo).resolve()
    output_path = (
        Path(args.output_path).resolve() if args.output_path
        else repo / ".tokenman" / "initial-scope.md"
    )

    try:
        profile = repo_profile.inspect(repo)
    except repo_profile.RepoProfileError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    plugins = marketplace.list_plugins(refresh=args.refresh)
    marketplaces_empty = not plugins

    try:
        root = catalog.tokenman_root()
        catalog_data = catalog.load_catalog(root)
    except catalog.SkillResolutionError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    answers = _ask_interactive(args.non_interactive)

    if args.dry_run:
        executor: scope_drafter.ScopeExecutor = scope_drafter.StubScopeExecutor(
            canned_result=_get_stub_result()
        )
    else:
        executor = scope_drafter.ClaudeScopeExecutor(claude_bin=args.claude_bin)

    try:
        draft = scope_drafter.draft(
            profile=profile, plugins=plugins, user_answers=answers,
            catalog=catalog_data, executor=executor, catalog_root=root,
            consumer_repo=repo,
        )
    except (scope_drafter.ScopeExecutorError, scope_drafter.ScopeDrafterError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 3

    rendered = _render_markdown(
        draft=draft, profile=profile, repo_name=repo.name,
        prompt_version="v1", marketplaces_empty=marketplaces_empty,
    )

    decision, final_md = _prompt_accept_edit_abort(rendered, args.non_interactive)
    if decision == "abort":
        print("aborted; no file written", file=sys.stderr)
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(final_md)
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
