"""Onboarding summary markdown renderer. Pure function over an
OnboardingResult — no I/O.

See docs/superpowers/specs/2026-04-18-phase-1-4-onboarding-mode-design.md §5.2.
"""
from __future__ import annotations

from datetime import datetime, timezone

from harness.lib.ledger import LedgerEntry
from harness.lib.onboarder import OnboardingResult


def _fmt_int(n: int) -> str:
    return f"{n:,}"


def _utilization_pct(total: int, ceiling: int) -> str:
    if ceiling <= 0:
        return "n/a"
    return f"{(100 * total / ceiling):.1f}%"


def _entry_line(entry: LedgerEntry) -> str:
    skill = entry["skill"]
    status = entry["status"]
    tokens = _fmt_int(entry["total_tokens"])
    if status == "pr_opened":
        tail = f"PR #{entry['pr']}"
    elif status == "no_change":
        tail = "no_change"
    elif status == "skipped_budget":
        tail = "skipped_budget"
    elif status == "error":
        tail = "error"
    else:
        tail = status
    return f"- **{skill}** — {status} ({tokens} tok) → {tail}"


def _pr_lines(entries: list[LedgerEntry]) -> list[str]:
    out = []
    for e in entries:
        if e["status"] != "pr_opened":
            continue
        gen = e.get("generator") or {}
        summary = gen.get("output_summary", "")
        out.append(f"- **#{e['pr']}**: {e['skill']} — {summary}")
    if not out:
        return [
            "None — every enabled skill produced no_change or was skipped."
        ]
    return out


def _considered_lines(entries: list[LedgerEntry]) -> list[str]:
    out = []
    for e in entries:
        if e["status"] != "no_change":
            continue
        gen = e.get("generator") or {}
        summary = gen.get("output_summary", "")
        out.append(f"- **{e['skill']}** — {summary}")
    if not out:
        return ["Every enabled skill proposed a change."]
    return out


def _skipped_lines(entries: list[LedgerEntry]) -> list[str]:
    out = []
    for e in entries:
        status = e["status"]
        if status == "skipped_budget":
            out.append(
                f"- **{e['skill']}** — session token ceiling reached "
                "before this skill ran"
            )
        elif status == "error":
            out.append(
                f"- **{e['skill']}** — executor or PR-opener failed; "
                f"see runs/{e['run_id']}/executor.stderr"
            )
    if not out:
        return ["Nothing was skipped."]
    return out


def build(
    *,
    result: OnboardingResult,
    repo_name: str,
    today: datetime | None = None,
) -> str:
    """Render an OnboardingResult to the markdown documented in spec §5.2."""
    when = (today or datetime.now(timezone.utc)).strftime("%Y-%m-%d")
    duration = int((result.finished_at - result.started_at).total_seconds())
    util = _utilization_pct(result.total_tokens, result.session_ceiling)

    lines: list[str] = []
    lines.append(f"# Tokenman — Onboarding summary for {repo_name}")
    lines.append("")
    lines.append(
        f"_Generated by `python -m harness.onboard` on {when} "
        f"in {duration}s._"
    )
    lines.append(
        f"_Total tokens: {_fmt_int(result.total_tokens)}  "
        f"Session ceiling: {_fmt_int(result.session_ceiling)}  "
        f"Utilization: {util}_"
    )
    lines.append("")

    lines.append("## What ran")
    lines.append("")
    for e in result.entries:
        lines.append(_entry_line(e))
    lines.append("")

    lines.append("## Pull requests opened")
    lines.append("")
    lines.extend(_pr_lines(result.entries))
    lines.append("")

    lines.append("## What was considered but not proposed")
    lines.append("")
    lines.extend(_considered_lines(result.entries))
    lines.append("")

    lines.append("## What was skipped")
    lines.append("")
    lines.extend(_skipped_lines(result.entries))
    lines.append("")

    lines.append("## Next steps")
    lines.append("")
    lines.append("- Review the PRs above at your pace.")
    lines.append("- Edit `.tokenman/CLAUDE.md` to teach the harness boundaries.")
    lines.append(
        "- Edit `.tokenman/tokenman.yaml` to add/remove skills "
        "or adjust schedule."
    )
    lines.append(
        "- Re-run onboarding any time: "
        "`gh workflow run tokenman.yml -f mode=onboarding`"
    )
    lines.append("")

    return "\n".join(lines)
